var Excel = require('exceljs');
var path = require('path');
const fs = require('file-system');
const result = "./outpuFile/result.txt";

    function leer_archivo(archivo){

        var wb = new Excel.Workbook();
        

        wb.xlsx.readFile("./inputFile/"+archivo+".xlsx").then(function(err, data){
            
            var sh = wb.getWorksheet("SQL Results");
            
          var data="<?xml version='1.0' encoding='UTF-8' ?>\n<!-- Generated by Oracle DVM Editor version 1.0 at [2/4/20 11:18 AM]. -->\n<dvm name='NOMBRE_DVM' xmlns='http://xmlns.oracle.com/dvm'>\n  <description></description>\n<columns>\n\t<column name='NOMBRE_COLUMNA'/>\n\t<column name='NOMBRE_COLUMNA'/>\n</columns>\n<rows>\n<row>\n";
           
             //ROWS
            for (i = 2; i <= sh.rowCount; i++) {
                if(i>2){
                    data="<row>\n";
                }
                
               //COLUMNS
              
               for (j=1; j<=sh.columnCount; j++){
                    data=data+"\t<cell>"+sh.getRow(i).getCell(j).value+"</cell>\n";
               }
               data=data+"</row>\n";
               
               fs.appendFileSync(result,data,'utf8',(err,result)=>{
                if(err){
                    console.log(err);
                }
            });
        }

            fs.appendFileSync(result,"\n</rows>\n</dvm>",'utf8',(err,result)=>{
                if(err){
                    console.log(err);
                }

            
        });
    
    
    });
}
module.exports= {

    leer_archivo

    }
